output: docs
author: gematik GmbH
author_url: https://www.gematik.de
exclude: /*/internal*
github_url: https://github.com/gematik/E-Rezept-App-iOS
theme: fullwidth
swift_build_tool: xcodebuild
documentation:
  - build/docs/generated/*.md
  - doc/manual/*.md
  - doc/modules/eRpApp/*.md
xcodebuild_arguments:
  - "-project"
  - 'eRp-App.xcodeproj'
  - "-scheme"
  - 'eRpApp'
  - '-destination'
  - 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
