configurations:
  - sources: # writes to Sources/eRpApp/Generated/
      - Sources
    templates:
      - Templates/Sourcery/eRpApp
    output: Sources
  - sources: # writes to Tests/AVSTests/Mocks/Generated/
      - Sources
      - Tests/AVSTests
    templates:
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/AVSTests
    args:
      autoMockableImports: [ Combine,Foundation,HTTPClient,OpenSSL ]
      autoMockableTestableImports: [ AVS ]
  - sources: # writes to Tests/eRpAppTests/Mocks/Generated/
      - Sources
      - Tests/eRpAppTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/eRpAppTests
    args:
      protocolMockImports: [ AVS,Combine,eRpKit,eRpLocalStorage,eRpRemoteStorage,Foundation,IdentifiedCollections,IDP,OpenSSL,Pharmacy,TestUtils,TrustStore,VAUClient, ZXingCpp ]
      protocolMockTestableImports: [ eRpFeatures ]
      autoMockableImports: [ AVS, BfArM, Combine,eRpKit,eRpLocalStorage,eRpRemoteStorage,Foundation,IdentifiedCollections,IDP,OpenSSL,Pharmacy,TestUtils,TrustStore,VAUClient, ZXingCpp ]
      autoMockableTestableImports: [ eRpFeatures ]
  - sources: # writes to Tests/eRpKitTests/Mocks/Generated/
      - Sources
      - Tests/eRpKitTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/eRpKitTests
    args:
      protocolMockImports: [ Combine,eRpKit,Foundation ]
      protocolMockTestableImports: [ eRpKit ]
      autoMockableImports: [ Combine,eRpKit,Foundation ]
      autoMockableTestableImports: [ eRpKit ]
  - sources: # writes to Tests/eRpLocalStorageTests/Mocks/Generated/
      - Sources
      - Tests/eRpLocalStorageTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/eRpLocalStorageTests
    args:
      protocolMockImports: [ Combine,eRpKit,Foundation ]
      protocolMockTestableImports: [ eRpLocalStorage ]
      autoMockableImports: [ Combine,eRpKit,Foundation ]
      autoMockableTestableImports: [ eRpLocalStorage ]
  - sources: # writes to Tests/IDPTests/Mocks/Generated/
      - Sources
      - Tests/IDPTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/IDPTests
    args:
      protocolMockImports: [ Combine,Foundation,HTTPClient,OpenSSL,TrustStore ]
      protocolMockTestableImports: [ IDP ]
      autoMockableImports: [ Combine,Foundation,HTTPClient,OpenSSL,TrustStore ]
      autoMockableTestableImports: [ IDP ]
  - sources: # writes to Tests/IDPLiveTests/Mocks/Generated/
      - Sources
      - Tests/IDPLiveTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/IDPLiveTests
    args:
      protocolMockImports: [ Combine,Foundation,HTTPClient,IDP,OpenSSL,TrustStore ]
      protocolMockTestableImports: [ IDPLive ]
      autoMockableImports: [ Combine,Foundation,HTTPClient,IDP,OpenSSL,TrustStore ]
      autoMockableTestableImports: [ IDPLive ]
  - sources: # writes to Tests/IntegrationTests/Mocks/Generated/
      - Sources
      - Tests/IntegrationTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/IntegrationTests
    args:
      protocolMockImports: [ Combine,eRpKit,OpenSSL,TrustStore ]
      protocolMockTestableImports: [ Pharmacy ]
      autoMockableImports: [ Combine,eRpKit,OpenSSL,TrustStore ]
      autoMockableTestableImports: [ Pharmacy ]
  - sources: # writes to Tests/PharmacyTests/Mocks/Generated/
      - Sources
      - Tests/PharmacyTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/PharmacyTests
    args:
      protocolMockImports: [ Combine,eRpKit,OpenSSL ]
      protocolMockTestableImports: [ Pharmacy ]
      autoMockableImports: [ Combine,eRpKit,OpenSSL ]
      autoMockableTestableImports: [ Pharmacy ]
  - sources: # writes to Tests/TrustStoreTests/Mocks/Generated/
      - Sources
      - Tests/TrustStoreTests
    templates:
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/TrustStoreTests
    args:
      autoMockableImports: [ Combine,Foundation,OpenSSL ]
      autoMockableTestableImports: [ TrustStore ]
  - sources:  # writes to Tests/VAUClientTests/Mocks/Generated/
      - Sources
      - Tests/VAUClientTests
    templates:
      - Templates/Sourcery/Tests/ProtocolMock.stencil
      - Templates/Sourcery/Tests/AutoMockable.stencil
    output: Tests/VAUClientTests
    args:
      protocolMockImports: [ Combine,Foundation,OpenSSL,TrustStore ]
      protocolMockTestableImports: [ VAUClient ]
      autoMockableImports: [ Combine,Foundation,OpenSSL,TrustStore ]
      autoMockableTestableImports: [ VAUClient ]
