disabled_rules: # rule identifiers to exclude from running
  - trailing_comma
  - operator_whitespace
opt_in_rules:
  - attributes
  - empty_count
  - force_unwrapping
  - unneeded_parentheses_in_closure_argument
  - unavailable_function
  - trailing_closure
  - strict_fileprivate
  - sorted_imports
  - sorted_first_last
  - single_test_class
  - required_enum_case
  - redundant_type_annotation
  - redundant_nil_coalescing
  - prohibited_super_call
  - override_in_extension
  - overridden_super_call
  - operator_usage_whitespace
  - no_extension_access_modifier
  - multiline_function_chains
  - multiline_arguments
  - modifier_order
  - missing_docs
  - lower_acl_than_parent
  - literal_expression_end_indentation
  - first_where
  - file_name
  - fatal_error_message
  - explicit_init
  - empty_xctest_method
  - empty_string
  - discouraged_optional_collection
  - closure_end_indentation
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Package.swift
  - .build/
  - vendor/
  - DerivedData/
  - Sources/eRpApp/Generated/*
  - Sources/eRpStyleKit/Generated/*
  - Sources/eRpApp/UITestScenarios/SmartMock.generated.swift
  - Tests/*/Mocks/Generated/*
nesting:
  type_level: 3
line_length: 120
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_Previews"]
attributes:
  always_on_same_line: ["@Environment", "@ViewBuilder", "@Dependency", "@AppStorage"]
custom_rules:
  nimble_fail_with_description:
    included: ".*Test\\.swift"
    name: "Fail with description"
    regex: "(Nimble.fail\\(\\))"
    message: "Failures need a description"
    severity: warning
  must_not_contain_author:
    included:
      - ".*Test\\.swift"
      - ".*Sources\\.swift"
    name: "must not contain author"
    regex: "(\/\/[[:space:]]*Created by)"
    message: "Source must not contain author"
    severity: warning

