name: eRp-App
options:
  bundleIdPrefix: de.gematik.erp4ios.eRezept
  createIntermediateGroups: true
  developmentLanguage: en-GB
  useBaseInternationalization: false
  deploymentTarget:
    macOS: 11
    iOS: 15.0
schemes:
  AllTests_iOS:
    build:
      targets:
        eRpApp: all
    test:
      language: de    
      region: DE
      gatherCoverageData: true
      coverageTargets:
        - eRpApp
      targets:
        - eRpAppTests
        - eRpAppStoreScreenshots
        - eRpKitTests_iOS
        - eRpStyleKitTests_iOS
        - eRpLocalStorageTests_iOS
        - eRpRemoteStorageTests_iOS
        - PharmacyTests_iOS
        - IDPTests_iOS
        - HTTPClientTests_iOS
        - FHIRClientTests_iOS
        - TrustStoreTests_iOS
        - VAUClientTests_iOS
  AllTests_macOS:
    build:
      targets:
        eRpKit_macOS: test
    test:
      language: de  
      region: DE
      gatherCoverageData: true
      targets:
        - eRpKitTests_macOS
        - eRpLocalStorageTests_macOS
        - eRpRemoteStorageTests_macOS
        - PharmacyTests_macOS
        - IDPTests_macOS
        - HTTPClientTests_macOS
        - FHIRClientTests_macOS
        - TrustStoreTests_macOS
        - VAUClientTests_macOS
  AllIntegrationTests_iOS:
    build:
      targets:
        IntegrationTests_iOS: test
    test:
      language: de  
      region: DE
      targets:
        - IntegrationTests_iOS
      environmentVariables:
        - variable: APP_CONF
          value: $(APP_CONF)
          isEnabled: true
  StoreScreenshots_iOS:
    build:
      targets:
        IntegrationTests_iOS: test
    test:
      language: de 
      region: DE 
      targets:
        - eRpAppStoreScreenshots
packages:
  FHIRModels:
    url: https://github.com/apple/FHIRModels
    version: 0.4.0
  BundleKit:
    url: https://github.com/SwiftCommon/BundleKit
    majorVersion: 0.0.2
  Nimble:
    url: https://github.com/Quick/Nimble
    majorVersion: 10.0.0
  ZXingObjC:
    url: https://github.com/zxingify/zxingify-objc
    majorVersion: 3.6.7
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    majorVersion: 1.10.0
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    majorVersion: 0.5.3
  SwiftUI-Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect
    majorVersion: 0.1.3
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs
    majorVersion: 9.1.0
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 0.49.2
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    majorVersion: 0.7.0
  ComposableCoreLocation:
    url: https://github.com/pointfreeco/composable-core-location
    majorVersion: 0.1.0
  Zxcvbn:
    url: https://github.com/andyjohns/zxcvbn-ios
    revision: bf6083dc17df950c8bdfcf2063859ee1270015fd
  ContentSquare:
    url:  https://github.com/ContentSquare/CS_iOS_SDK.git
    majorVersion: 4.16.0
settings:
  base:
    # for DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC see: https://developer.apple.com/forums/thread/128806
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: 1
    CURRENT_PROJECT_VERSION: -1
    CODE_SIGN_IDENTITY: ""
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  eRpApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${GEM_PRODUCT_BUNDLE_IDENTIFIER}
        TARGETED_DEVICE_FAMILY: 1
    configFiles:
      Debug: Sources/eRpApp/Resources/debug.xcconfig
      Release: Sources/eRpApp/Resources/release.xcconfig
    sources:
      - Sources/eRpApp
    dependencies:
      - target: eRpStyleKit_iOS
      - target: eRpRemoteStorage_iOS
      - target: eRpKit_iOS
      - target: eRpLocalStorage_iOS
      - target: Pharmacy_iOS
      - target: IDP_iOS
      - target: HTTPClient_iOS
      - target: FHIRClient_iOS
      - target: TrustStore_iOS
      - target: VAUClient_iOS
      - target: AVS_iOS
      - framework: Carthage/Build/OpenSSL.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/CardReaderProviderApi.xcframework
      - framework: Carthage/Build/CardReaderAccess.xcframework
      - framework: Carthage/Build/NFCCardReaderProvider.xcframework
      - framework: Carthage/Build/ASN1Kit.xcframework
      - framework: Carthage/Build/HealthCardAccess.xcframework
      - framework: Carthage/Build/HealthCardControl.xcframework
      - framework: Carthage/Build/Helper.xcframework
      - sdk: CoreNFC.framework
      - sdk: Combine.framework
      - sdk: SwiftUI.framework
      - package: ZXingObjC
      - package: SwiftUI-Introspect
        product: Introspect
      - package: CombineSchedulers
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: ComposableCoreLocation
        product: ComposableCoreLocation
      - package: Zxcvbn
        product: Zxcvbn
      - package: ContentSquare
        product: ContentsquareModule
    scheme:
      testTargets:
        - eRpAppTests
      gatherCoverageData: false
  AVS:
    settings:
      PRODUCT_NAME: AVS
      INFOPLIST_FILE: Sources/AVS/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/AVS
    dependencies:
      - target: HTTPClient_${platform}
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/OpenSSL.xcframework
    scheme:
      testTargets:
        - AVSTests_${platform}
      gatherCoverageData: true
  eRpStyleKit:
    settings:
      PRODUCT_NAME: eRpStyleKit
      INFOPLIST_FILE: Sources/eRpStyleKit/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/eRpApp/Resources/Assets.xcassets
      - Sources/eRpApp/Generated/XCAssets+Generated.swift
      - Sources/eRpApp/Helper/Swiftgen/BundleToken+Helper.swift
      - Sources/eRpApp/Components/Colors.swift
      - Sources/eRpApp/Common/SFSymbolName.swift
      - Sources/eRpStyleKit
    dependencies:
      - sdk: SwiftUI.framework
    scheme:
      testTargets:
        - eRpStyleKitTests_${platform}
      gatherCoverageData: true
  eRpKit:
    settings:
      PRODUCT_NAME: eRpKit
      INFOPLIST_FILE: Sources/eRpKit/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/eRpKit
    dependencies:
      - target: IDP_${platform}
      - package: BundleKit
    scheme:
      testTargets:
        - eRpKitTests_${platform}
      gatherCoverageData: true
  eRpLocalStorage:
    settings:
      PRODUCT_NAME: eRpLocalStorage
      INFOPLIST_FILE: Sources/eRpLocalStorage/Resources/Info.plist
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG ENABLE_DEBUG_VIEW
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/eRpLocalStorage
    dependencies:
      - sdk: CoreData.framework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - target: eRpKit_${platform}
      - target: eRpRemoteStorage_${platform}
        link: true
      - package: FHIRModels
        product: ModelsR4
    scheme:
      testTargets:
        - eRpLocalStorageTests_${platform}
      gatherCoverageData: true
  eRpRemoteStorage:
    settings:
      PRODUCT_NAME: eRpRemoteStorage
      INFOPLIST_FILE: Sources/eRpRemoteStorage/Resources/Info.plist
    type: library.static
    platform: [iOS,macOS]
    sources:
      - Sources/eRpRemoteStorage
    dependencies:
      - target: eRpKit_${platform}
      - package: FHIRModels
        product: ModelsR4
      - target: HTTPClient_${platform}
      - target: FHIRClient_${platform}
    scheme:
      testTargets:
        - eRpRemoteStorageTests_${platform}
      gatherCoverageData: true
  Pharmacy:
    settings:
      PRODUCT_NAME: Pharmacy
      INFOPLIST_FILE: Sources/Pharmacy/Resources/Info.plist
    type: library.static
    platform: [iOS,macOS]
    sources:
      - Sources/Pharmacy
    dependencies:
      - package: FHIRModels
        product: ModelsR4
      - target: HTTPClient_${platform}
      - target: FHIRClient_${platform}
      - target: eRpKit_${platform}
    scheme:
      testTargets:
        - PharmacyTests_${platform}
      gatherCoverageData: true
  IDP:
    settings:
      PRODUCT_NAME: IDP
      INFOPLIST_FILE: Sources/IDP/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/IDP
    dependencies:
      - target: HTTPClient_${platform}
      - target: TrustStore_${platform}
      - framework: Carthage/Build/ASN1Kit.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/OpenSSL.xcframework
      - package: CombineSchedulers
    scheme:
      testTargets:
        - IDPTests_${platform}
      gatherCoverageData: true
  HTTPClient:
    settings:
      PRODUCT_NAME: HTTPClient
      INFOPLIST_FILE: Sources/HTTPClient/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/HTTPClient
    dependencies:
      - framework: Carthage/Build/GemCommonsKit.xcframework
    scheme:
      testTargets:
        - HTTPClientTests_${platform}
      gatherCoverageData: true
  FHIRClient:
    settings:
      PRODUCT_NAME: FHIRClient
      INFOPLIST_FILE: Sources/FHIRClient/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/FHIRClient
    dependencies:
      - package: FHIRModels
        product: ModelsR4
      - package: CombineSchedulers
      - framework: Carthage/Build/GemCommonsKit.xcframework
    scheme:
      testTargets:
        - FHIRClientTests_${platform}
      gatherCoverageData: true
  TestUtils:
    settings:
      INFOPLIST_FILE: Sources/TestUtils/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/TestUtils
    dependencies:
      - target: HTTPClient_${platform}
      - target: IDP_${platform}
      - target: VAUClient_${platform}
      - package: Nimble
      - sdk: XCTest.framework
    scheme:
  TrustStore:
    settings:
      PRODUCT_NAME: TrustStore
      INFOPLIST_FILE: Sources/TrustStore/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/TrustStore
    dependencies:
      - target: HTTPClient_${platform}
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/OpenSSL.xcframework
    scheme:
      testTargets:
        - TrustStoreTests_${platform}
      gatherCoverageData: true
  VAUClient:
    settings:
      PRODUCT_NAME: VAUClient
      INFOPLIST_FILE: Sources/VAU/Resources/Info.plist
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/VAU
    dependencies:
      - target: HTTPClient_${platform}
      - target: TrustStore_${platform}
      - framework: Carthage/Build/OpenSSL.xcframework
      - framework: Carthage/Build/DataKit.xcframework
    scheme:
      testTargets:
        - TrustStoreTests_${platform}
      gatherCoverageData: true
  AVSTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/AVSTests/Resources/Info.plist
    sources:
      - Tests/AVSTests
    dependencies:
      - target: AVS_${platform}
      - target: TestUtils_${platform}
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - package: Nimble
      - package: BundleKit
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  eRpAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/eRpAppTests/Resources/Info.plist
    sources:
      - path: Tests/eRpAppTests
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: TestUtils_iOS
      - target: eRpApp
      - package: Nimble
      - package: SnapshotTesting
  eRpAppStoreScreenshots:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/eRpAppStoreScreenshots/Resources/Info.plist
    sources:
      - path: Tests/eRpAppStoreScreenshots
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: TestUtils_iOS
      - target: eRpApp
      - package: Nimble
      - package: SnapshotTesting
  eRpKitTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/eRpKitTests/Resources/Info.plist
    sources:
      - Tests/eRpKitTests
    dependencies:
      - target: eRpKit_${platform}
      - target: TestUtils_${platform}
      - package: Nimble
  eRpStyleKitTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/eRpStyleKitTests/Resources/Info.plist
    sources:
      - Tests/eRpStyleKitTests
    dependencies:
      - target: eRpStyleKit_${platform}
      - package: SnapshotTesting
  eRpLocalStorageTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/eRpLocalStorageTests/Resources/Info.plist
    sources:
      - Tests/eRpLocalStorageTests
    dependencies:
      - target: eRpLocalStorage_${platform}
      - target: TestUtils_${platform}
      - package: Nimble
  eRpRemoteStorageTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/eRpRemoteStorageTests/Resources/Info.plist
    sources:
      - path: Tests/eRpRemoteStorageTests
    dependencies:
      - target: eRpRemoteStorage_${platform}
      - target: TestUtils_${platform}
      - package: BundleKit
      - package: Nimble
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  PharmacyTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/PharmacyTests/Resources/Info.plist
    sources:
      - path: Tests/PharmacyTests
    dependencies:
      - target: Pharmacy_${platform}
      - target: TestUtils_${platform}
      - package: BundleKit
      - package: Nimble
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  IDPTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/IDPTests/Resources/Info.plist
    sources:
      - path: Tests/IDPTests
        excludes:
          - "**/.swiftlint.yml"
    dependencies:
      - target: IDP_${platform}
      - target: TestUtils_${platform}
      - package: BundleKit
      - package: Nimble
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  HTTPClientTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/HTTPClientTests/Resources/Info.plist
    sources:
      - Tests/HTTPClientTests
    dependencies:
      - target: HTTPClient_${platform}
      - target: TestUtils_${platform}
      - package: BundleKit
      - package: Nimble
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  FHIRClientTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/FHIRClientTests/Resources/Info.plist
    sources:
      - Tests/FHIRClientTests
    dependencies:
      - target: FHIRClient_${platform}
      - target: TestUtils_${platform}
      - package: BundleKit
      - package: Nimble
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  TrustStoreTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/TrustStoreTests/Resources/Info.plist
    sources:
      - Tests/TrustStoreTests
    dependencies:
      - target: TrustStore_${platform}
      - target: TestUtils_${platform}
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - package: Nimble
      - package: BundleKit
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  VAUClientTests:
    type: bundle.unit-test
    platform: [iOS,macOS]
    settings:
      INFOPLIST_FILE: Tests/VAUTests/Resources/Info.plist
    sources:
      - Tests/VAUTests
    dependencies:
      - target: VAUClient_${platform}
      - target: TestUtils_${platform}
      - framework: Carthage/Build/ASN1Kit.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - package: Nimble
      - package: BundleKit
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
  IntegrationTests:
    type: bundle.unit-test
    platform: [iOS]
    settings:
      INFOPLIST_FILE: Tests/IntegrationTests/Resources/Info.plist
    sources:
      - Tests/IntegrationTests
    dependencies:
      - target: AVS_${platform}
      - target: eRpKit_${platform}
      - target: eRpApp
      - target: IDP_${platform}
      - target: TrustStore_${platform}
      - target: TestUtils_${platform}
      - target: VAUClient_${platform}
      - package: BundleKit
      - package: Nimble
buildImplicitDependencies: true
