name: eRp-App
options:
  bundleIdPrefix: de.gematik.erp4ios.eRezept
  createIntermediateGroups: true
  developmentLanguage: en-GB
  useBaseInternationalization: false
  deploymentTarget:
    macOS: 12.0
    iOS: 15.0
schemes:
  UITests_iOS:
    build:
      targets:
        eRpApp: all
    run:
      environmentVariables:
        - variable: UITEST.RECORD_MOCKS
          value: 1
          isEnabled: false
        - variable: UITEST.RESET
          value: 1
          isEnabled: false
        - variable: UITEST.DISABLE_ANIMATIONS
          value: YES
          isEnabled: false
        - variable: UITEST.DISABLE_AUTHENTICATION
          value: YES
          isEnabled: false
        - variable: UITEST.SCENARIO_NAME
          value: <SCENARIO>UITests
          isEnabled: false
    test:
      language: de
      region: DE
      gatherCoverageData: true
      coverageTargets:
        - eRpApp
      targets:
        - eRpAppUITests
      testPlans:
        - path: Tests/eRpAppUITests/Support/UITests_iOS.xctestplan
          defaultPlan: true
  AllTests_iOS:
    build:
      targets:
        eRpApp: all
    test:
      language: de
      region: DE
      gatherCoverageData: true
      coverageTargets:
        - eRpApp
      targets:
        - eRpAppTests
        - eRpAppStoreScreenshots
        - package: eRpKit/eRpStyleKitTests
        - package: eRpKit/eRpKitTests
        - package: eRpKit/eRpLocalStorageTests
        - package: eRpKit/eRpRemoteStorageTests
        - package: eRpKit/PharmacyTests
        - package: eRpKit/IDPTests
        - package: eRpKit/HTTPClientTests
        - package: eRpKit/FHIRClientTests
        - package: eRpKit/TrustStoreTests
        - package: eRpKit/VAUClientTests
        - package: eRpKit/AVSTests
  AllTests_macOS:
    build:
      targets:
        eRpDummy_macOS: test
    test:
      language: de
      region: DE
      gatherCoverageData: true
      targets:
        - package: eRpKit/eRpKitTests
        - package: eRpKit/eRpLocalStorageTests
        - package: eRpKit/eRpRemoteStorageTests
        - package: eRpKit/PharmacyTests
        - package: eRpKit/IDPTests
        - package: eRpKit/HTTPClientTests
        - package: eRpKit/FHIRClientTests
        - package: eRpKit/TrustStoreTests
        - package: eRpKit/VAUClientTests
  AllIntegrationTests_iOS:
    build:
      targets:
        IntegrationTests_iOS: test
    test:
      language: de
      region: DE
      targets:
        - IntegrationTests_iOS
      environmentVariables:
        - variable: APP_CONF
          value: $(APP_CONF)
          isEnabled: true
  StoreScreenshots_iOS:
    build:
      targets:
        IntegrationTests_iOS: test
    test:
      language: de
      region: DE
      targets:
        - eRpAppStoreScreenshots
packages:
  eRpKit:
    path: ./
  OpenHealthCardKit:
    url: https://github.com/gematik/ref-OpenHealthCardKit/
    majorVersion: 5.6.0   
  ASN1Kit:
    url: https://github.com/gematik/ASN1Kit
    majorVersion: 1.2.0
  DataKit:
    url: https://github.com/SwiftCommon/DataKit
    majorVersion: 1.1.0
  GemCommonsKit:
    url: https://github.com/gematik/ref-GemCommonsKit
    majorVersion: 1.3.0
  OpenSSL-Swift:
   url: https://github.com/gematik/OpenSSL-Swift
   majorVersion: 4.1.0
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    majorVersion: 0.7.0
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    majorVersion: 0.5.3  
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    minorVersion: 0.59.0
  ComposableCoreLocation:
    url: https://github.com/pointfreeco/composable-core-location
    minorVersion: 0.3.0
  IdentifiedCollections:
    url: https://github.com/pointfreeco/swift-identified-collections.git
    minorVersion: 0.8.0
  ContentSquare:
    url:  https://github.com/ContentSquare/CS_iOS_SDK
    majorVersion: 4.27.1
  FHIRModels:
    url: https://github.com/apple/FHIRModels
    version: 0.4.0
  Nimble:
    url: https://github.com/Quick/Nimble
    majorVersion: 9.2.0
    # majorVersion: 10.0.0
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs
    majorVersion: 9.1.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    majorVersion: 1.10.0
  SwiftUI-Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect
    majorVersion: 0.1.3
  Zxcvbn:
    url: https://github.com/andyjohns/zxcvbn-ios
    revision: bf6083dc17df950c8bdfcf2063859ee1270015fd
  ZXingObjC:
    url: https://github.com/zxingify/zxingify-objc
    majorVersion: 3.6.7
  GemPDFKit:
    url: https://github.com/gematik/swift-gemPDFKit
    majorVersion: 0.1.0
settings:
  base:
    # for DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC see: https://developer.apple.com/forums/thread/128806
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: 1
    CURRENT_PROJECT_VERSION: -1
    CODE_SIGN_IDENTITY: ""
    SWIFT_VERSION: 5.8
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  eRpDummy:
    type: framework
    platform: [macOS]
    sources:
      - Sources/eRpApp/Common/ProgressResponse.swift
  eRpApp:
    type: application
    platform: iOS
        # basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${GEM_PRODUCT_BUNDLE_IDENTIFIER}
        TARGETED_DEVICE_FAMILY: 1
    configFiles:
      Debug: Sources/eRpApp/Resources/debug.xcconfig
      Release: Sources/eRpApp/Resources/release.xcconfig
    sources:
      - Sources/eRpApp
    dependencies:
      - package: eRpKit
        product: eRpStyleKit
      - package: eRpKit
        product: eRpKit
      - package: eRpKit
        product: eRpRemoteStorage
      - package: eRpKit
        product: eRpLocalStorage
      - package: eRpKit
        product: Pharmacy
      - package: eRpKit
        product: AVS
      - package: eRpKit
        product: IDP
      - package: eRpKit
        product: FHIRClient
      - package: eRpKit
        product: HTTPClient
      - package: eRpKit
        product: TrustStore
      - package: eRpKit
        product: VAUClient
      - package: OpenSSL-Swift
      - package: DataKit
      - package: GemCommonsKit
        product: GemCommonsKit
      - package: OpenHealthCardKit
        product: CardReaderProviderApi
      - package: OpenHealthCardKit
        product: NFCCardReaderProvider
      - package: ASN1Kit
      - package: OpenHealthCardKit
        product: HealthCardAccess
      - package: OpenHealthCardKit
        product: HealthCardControl
      - package: OpenHealthCardKit
        product: Helper
      - sdk: CoreNFC.framework
      - sdk: Combine.framework
      - sdk: SwiftUI.framework
      - package: ZXingObjC
      - package: SwiftUI-Introspect
        product: Introspect
      - package: CombineSchedulers
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: ComposableCoreLocation
        product: ComposableCoreLocation
      - package: Zxcvbn
        product: Zxcvbn
      - package: ContentSquare
        product: ContentsquareModule
      - package: GemPDFKit
        product: GemPDFKit
    scheme:
      language: de
      region: DE
      testTargets:
        - eRpAppTests
      gatherCoverageData: false
  eRpAppUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/eRpAppUITests/Support/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: de.gematik.eRpAppUITests
      DEVELOPMENT_TEAM: A9FL89PFFL
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: Apple Development
    sources:
      - path: Tests/eRpAppUITests/Support/empty.xcappdata
        buildPhase: none
        type: file
      - path: Tests/eRpAppUITests/Support/UITests_iOS.xctestplan
        buildPhase: none
      - path: Tests/eRpAppUITests/Support/Info.plist
        buildPhase: none
      - path: Tests/eRpAppUITests/Tests
      - path: Sources/eRpApp/Generated/Accessibility+Generated.swift
    dependencies:
      - target: eRpApp
      - package: Nimble
      - package: SnapshotTesting
  eRpAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/eRpAppTests/Resources/Info.plist
    sources:
      - path: Tests/eRpAppTests
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: eRpApp
      - package: eRpKit
        product: TestUtils
      - package: Nimble
      - package: SnapshotTesting
  eRpAppStoreScreenshots:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/eRpAppStoreScreenshots/Resources/Info.plist
    sources:
      - path: Tests/eRpAppStoreScreenshots
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: eRpApp
      - package: eRpKit
        product: TestUtils
      - package: Nimble
      - package: SnapshotTesting
  IntegrationTests:
    type: bundle.unit-test
    platform: [iOS]
    settings:
      INFOPLIST_FILE: Tests/IntegrationTests/Resources/Info.plist
    sources:
      - Tests/IntegrationTests
    dependencies:
      - target: eRpApp
      - package: eRpKit
        product: eRpKit
      - package: eRpKit 
        product: AVS
      - package: eRpKit  
        product: IDP
      - package: eRpKit 
        product: TrustStore
      - package: eRpKit  
        product: TestUtils
      - package: eRpKit   
        product: VAUClient
      - package: Nimble
buildImplicitDependencies: true
