//
//  Copyright (c) 2022 gematik GmbH
//  
//  Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
//  the European Commission - subsequent versions of the EUPL (the Licence);
//  You may not use this work except in compliance with the Licence.
//  You may obtain a copy of the Licence at:
//  
//      https://joinup.ec.europa.eu/software/page/eupl
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the Licence is distributed on an "AS IS" basis,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the Licence for the specific language governing permissions and
//  limitations under the Licence.
//  
//

import eRpKit
import Foundation
import ModelsR4

// swiftlint:disable:next type_body_length
struct PrescriptionKBVKeyMapping {
    internal static func localizedStringKeyForMemberStatusKey(_ key: String) -> String? {
        let mapping = [
            "1": "kbv_member_status_1",
            "3": "kbv_member_status_3",
            "5": "kbv_member_status_5",
        ]
        return mapping[key]
    }

    internal static func localizedStringKeyForNormSizeKey(_ key: String) -> String? {
        let mapping = [
            "ka": "kbv_norm_size_ka",
            "ktp": "kbv_norm_size_ktp",
            "n1": "kbv_norm_size_n1",
            "n2": "kbv_norm_size_n2",
            "n3": "kbv_norm_size_n3",
            "nb": "kbv_norm_size_nb",
            "sonstiges": "kbv_norm_size_sonstiges",
        ]
        return mapping[key.lowercased()]
    }

    // swiftlint:disable:next function_body_length
    internal static func localizedStringKeyForDosageFormKey(_ key: String) -> String? {
        let mapping = [
            "---": "kbv_code_dosage_form_none",
            "aeo": "kbv_code_dosage_form_aeo",
            "amp": "kbv_code_dosage_form_amp",
            "apa": "kbv_code_dosage_form_apa",
            "asn": "kbv_code_dosage_form_asn",
            "aso": "kbv_code_dosage_form_aso",
            "ato": "kbv_code_dosage_form_ato",
            "atr": "kbv_code_dosage_form_atr",
            "aub": "kbv_code_dosage_form_aub",
            "auc": "kbv_code_dosage_form_auc",
            "aug": "kbv_code_dosage_form_aug",
            "aus": "kbv_code_dosage_form_aus",
            "bad": "kbv_code_dosage_form_bad",
            "bal": "kbv_code_dosage_form_bal",
            "ban": "kbv_code_dosage_form_ban",
            "beu": "kbv_code_dosage_form_beu",
            "bin": "kbv_code_dosage_form_bin",
            "bon": "kbv_code_dosage_form_bon",
            "bpl": "kbv_code_dosage_form_bpl",
            "bre": "kbv_code_dosage_form_bre",
            "bta": "kbv_code_dosage_form_bta",
            "cre": "kbv_code_dosage_form_cre",
            "dfl": "kbv_code_dosage_form_dfl",
            "dig": "kbv_code_dosage_form_dig",
            "dil": "kbv_code_dosage_form_dil",
            "dis": "kbv_code_dosage_form_dis",
            "dka": "kbv_code_dosage_form_dka",
            "dos": "kbv_code_dosage_form_dos",
            "dra": "kbv_code_dosage_form_dra",
            "drm": "kbv_code_dosage_form_drm",
            "dsc": "kbv_code_dosage_form_dsc",
            "dss": "kbv_code_dosage_form_dss",
            "edp": "kbv_code_dosage_form_edp",
            "ein": "kbv_code_dosage_form_ein",
            "ele": "kbv_code_dosage_form_ele",
            "eli": "kbv_code_dosage_form_eli",
            "emu": "kbv_code_dosage_form_emu",
            "ess": "kbv_code_dosage_form_ess",
            "esu": "kbv_code_dosage_form_esu",
            "ext": "kbv_code_dosage_form_ext",
            "fbe": "kbv_code_dosage_form_fbe",
            "fbw": "kbv_code_dosage_form_fbw",
            "fda": "kbv_code_dosage_form_fda",
            "fer": "kbv_code_dosage_form_fer",
            "fet": "kbv_code_dosage_form_fet",
            "fla": "kbv_code_dosage_form_fla",
            "fle": "kbv_code_dosage_form_fle",
            "flu": "kbv_code_dosage_form_flu",
            "fmr": "kbv_code_dosage_form_fmr",
            "fol": "kbv_code_dosage_form_fol",
            "frb": "kbv_code_dosage_form_frb",
            "fse": "kbv_code_dosage_form_fse",
            "fta": "kbv_code_dosage_form_fta",
            "gek": "kbv_code_dosage_form_gek",
            "gel": "kbv_code_dosage_form_gel",
            "gli": "kbv_code_dosage_form_gli",
            "glo": "kbv_code_dosage_form_glo",
            "gmr": "kbv_code_dosage_form_gmr",
            "gpa": "kbv_code_dosage_form_gpa",
            "gra": "kbv_code_dosage_form_gra",
            "gse": "kbv_code_dosage_form_gse",
            "gul": "kbv_code_dosage_form_gul",
            "has": "kbv_code_dosage_form_has",
            "hkm": "kbv_code_dosage_form_hkm",
            "hkp": "kbv_code_dosage_form_hkp",
            "hpi": "kbv_code_dosage_form_hpi",
            "hvw": "kbv_code_dosage_form_hvw",
            "ifa": "kbv_code_dosage_form_ifa",
            "ifb": "kbv_code_dosage_form_ifb",
            "ifd": "kbv_code_dosage_form_ifd",
            "ife": "kbv_code_dosage_form_ife",
            "iff": "kbv_code_dosage_form_iff",
            "ifk": "kbv_code_dosage_form_ifk",
            "ifl": "kbv_code_dosage_form_ifl",
            "ifs": "kbv_code_dosage_form_ifs",
            "iha": "kbv_code_dosage_form_iha",
            "ihp": "kbv_code_dosage_form_ihp",
            "iie": "kbv_code_dosage_form_iie",
            "iil": "kbv_code_dosage_form_iil",
            "iim": "kbv_code_dosage_form_iim",
            "ika": "kbv_code_dosage_form_ika",
            "ilo": "kbv_code_dosage_form_ilo",
            "imp": "kbv_code_dosage_form_imp",
            "inf": "kbv_code_dosage_form_inf",
            "inh": "kbv_code_dosage_form_inh",
            "ini": "kbv_code_dosage_form_ini",
            "inl": "kbv_code_dosage_form_inl",
            "ins": "kbv_code_dosage_form_ins",
            "ist": "kbv_code_dosage_form_ist",
            "isu": "kbv_code_dosage_form_isu",
            "iup": "kbv_code_dosage_form_iup",
            "kan": "kbv_code_dosage_form_kan",
            "kap": "kbv_code_dosage_form_kap",
            "kat": "kbv_code_dosage_form_kat",
            "kda": "kbv_code_dosage_form_kda",
            "keg": "kbv_code_dosage_form_keg",
            "ker": "kbv_code_dosage_form_ker",
            "kgu": "kbv_code_dosage_form_kgu",
            "kid": "kbv_code_dosage_form_kid",
            "kii": "kbv_code_dosage_form_kii",
            "kks": "kbv_code_dosage_form_kks",
            "kli": "kbv_code_dosage_form_kli",
            "klt": "kbv_code_dosage_form_klt",
            "kmp": "kbv_code_dosage_form_kmp",
            "kmr": "kbv_code_dosage_form_kmr",
            "kod": "kbv_code_dosage_form_kod",
            "kom": "kbv_code_dosage_form_kom",
            "kon": "kbv_code_dosage_form_kon",
            "kpg": "kbv_code_dosage_form_kpg",
            "kri": "kbv_code_dosage_form_kri",
            "kss": "kbv_code_dosage_form_kss",
            "ksu": "kbv_code_dosage_form_ksu",
            "kta": "kbv_code_dosage_form_kta",
            "lan": "kbv_code_dosage_form_lan",
            "lii": "kbv_code_dosage_form_lii",
            "liq": "kbv_code_dosage_form_liq",
            "loe": "kbv_code_dosage_form_loe",
            "lot": "kbv_code_dosage_form_lot",
            "lov": "kbv_code_dosage_form_lov",
            "lse": "kbv_code_dosage_form_lse",
            "lta": "kbv_code_dosage_form_lta",
            "lup": "kbv_code_dosage_form_lup",
            "lut": "kbv_code_dosage_form_lut",
            "mil": "kbv_code_dosage_form_mil",
            "mis": "kbv_code_dosage_form_mis",
            "mix": "kbv_code_dosage_form_mix",
            "mrg": "kbv_code_dosage_form_mrg",
            "mrp": "kbv_code_dosage_form_mrp",
            "mta": "kbv_code_dosage_form_mta",
            "muw": "kbv_code_dosage_form_muw",
            "nag": "kbv_code_dosage_form_nag",
            "nao": "kbv_code_dosage_form_nao",
            "nas": "kbv_code_dosage_form_nas",
            "naw": "kbv_code_dosage_form_naw",
            "nds": "kbv_code_dosage_form_nds",
            "nsa": "kbv_code_dosage_form_nsa",
            "ntr": "kbv_code_dosage_form_ntr",
            "ocu": "kbv_code_dosage_form_ocu",
            "oel": "kbv_code_dosage_form_oel",
            "oht": "kbv_code_dosage_form_oht",
            "ovu": "kbv_code_dosage_form_ovu",
            "pam": "kbv_code_dosage_form_pam",
            "pas": "kbv_code_dosage_form_pas",
            "pel": "kbv_code_dosage_form_pel",
            "pen": "kbv_code_dosage_form_pen",
            "per": "kbv_code_dosage_form_per",
            "pfl": "kbv_code_dosage_form_pfl",
            "pft": "kbv_code_dosage_form_pft",
            "phi": "kbv_code_dosage_form_phi",
            "phv": "kbv_code_dosage_form_phv",
            "pie": "kbv_code_dosage_form_pie",
            "pif": "kbv_code_dosage_form_pif",
            "pii": "kbv_code_dosage_form_pii",
            "pij": "kbv_code_dosage_form_pij",
            "pik": "kbv_code_dosage_form_pik",
            "pis": "kbv_code_dosage_form_pis",
            "piv": "kbv_code_dosage_form_piv",
            "pki": "kbv_code_dosage_form_pki",
            "ple": "kbv_code_dosage_form_ple",
            "plf": "kbv_code_dosage_form_plf",
            "plg": "kbv_code_dosage_form_plg",
            "plh": "kbv_code_dosage_form_plh",
            "pli": "kbv_code_dosage_form_pli",
            "plk": "kbv_code_dosage_form_plk",
            "pls": "kbv_code_dosage_form_pls",
            "plv": "kbv_code_dosage_form_plv",
            "ppl": "kbv_code_dosage_form_ppl",
            "prs": "kbv_code_dosage_form_prs",
            "pse": "kbv_code_dosage_form_pse",
            "pst": "kbv_code_dosage_form_pst",
            "pud": "kbv_code_dosage_form_pud",
            "pul": "kbv_code_dosage_form_pul",
            "red": "kbv_code_dosage_form_red",
            "rek": "kbv_code_dosage_form_rek",
            "ret": "kbv_code_dosage_form_ret",
            "rgr": "kbv_code_dosage_form_rgr",
            "rka": "kbv_code_dosage_form_rka",
            "rms": "kbv_code_dosage_form_rms",
            "rsc": "kbv_code_dosage_form_rsc",
            "rsu": "kbv_code_dosage_form_rsu",
            "rut": "kbv_code_dosage_form_rut",
            "saf": "kbv_code_dosage_form_saf",
            "sal": "kbv_code_dosage_form_sal",
            "sam": "kbv_code_dosage_form_sam",
            "sch": "kbv_code_dosage_form_sch",
            "sei": "kbv_code_dosage_form_sei",
            "sha": "kbv_code_dosage_form_sha",
            "sir": "kbv_code_dosage_form_sir",
            "slz": "kbv_code_dosage_form_slz",
            "smf": "kbv_code_dosage_form_smf",
            "smt": "kbv_code_dosage_form_smt",
            "smu": "kbv_code_dosage_form_smu",
            "spa": "kbv_code_dosage_form_spa",
            "spf": "kbv_code_dosage_form_spf",
            "spl": "kbv_code_dosage_form_spl",
            "spr": "kbv_code_dosage_form_spr",
            "spt": "kbv_code_dosage_form_spt",
            "sri": "kbv_code_dosage_form_sri",
            "ssu": "kbv_code_dosage_form_ssu",
            "sta": "kbv_code_dosage_form_sta",
            "stb": "kbv_code_dosage_form_stb",
            "sti": "kbv_code_dosage_form_sti",
            "str": "kbv_code_dosage_form_str",
            "sub": "kbv_code_dosage_form_sub",
            "sue": "kbv_code_dosage_form_sue",
            "sul": "kbv_code_dosage_form_sul",
            "sup": "kbv_code_dosage_form_sup",
            "sus": "kbv_code_dosage_form_sus",
            "sut": "kbv_code_dosage_form_sut",
            "suv": "kbv_code_dosage_form_suv",
            "swa": "kbv_code_dosage_form_swa",
            "tab": "kbv_code_dosage_form_tab",
            "tae": "kbv_code_dosage_form_tae",
            "tam": "kbv_code_dosage_form_tam",
            "tee": "kbv_code_dosage_form_tee",
            "tei": "kbv_code_dosage_form_tei",
            "tes": "kbv_code_dosage_form_tes",
            "tin": "kbv_code_dosage_form_tin",
            "tka": "kbv_code_dosage_form_tka",
            "tle": "kbv_code_dosage_form_tle",
            "tmr": "kbv_code_dosage_form_tmr",
            "ton": "kbv_code_dosage_form_ton",
            "tpn": "kbv_code_dosage_form_tpn",
            "tpo": "kbv_code_dosage_form_tpo",
            "tra": "kbv_code_dosage_form_tra",
            "tri": "kbv_code_dosage_form_tri",
            "tro": "kbv_code_dosage_form_tro",
            "trs": "kbv_code_dosage_form_trs",
            "trt": "kbv_code_dosage_form_trt",
            "tsa": "kbv_code_dosage_form_tsa",
            "tsd": "kbv_code_dosage_form_tsd",
            "tse": "kbv_code_dosage_form_tse",
            "tss": "kbv_code_dosage_form_tss",
            "tst": "kbv_code_dosage_form_tst",
            "tsy": "kbv_code_dosage_form_tsy",
            "ttr": "kbv_code_dosage_form_ttr",
            "tub": "kbv_code_dosage_form_tub",
            "tue": "kbv_code_dosage_form_tue",
            "tup": "kbv_code_dosage_form_tup",
            "tvw": "kbv_code_dosage_form_tvw",
            "uta": "kbv_code_dosage_form_uta",
            "val": "kbv_code_dosage_form_val",
            "var": "kbv_code_dosage_form_var",
            "vcr": "kbv_code_dosage_form_vcr",
            "ver": "kbv_code_dosage_form_ver",
            "vge": "kbv_code_dosage_form_vge",
            "vka": "kbv_code_dosage_form_vka",
            "vli": "kbv_code_dosage_form_vli",
            "vov": "kbv_code_dosage_form_vov",
            "vst": "kbv_code_dosage_form_vst",
            "vsu": "kbv_code_dosage_form_vsu",
            "vta": "kbv_code_dosage_form_vta",
            "wat": "kbv_code_dosage_form_wat",
            "wga": "kbv_code_dosage_form_wga",
            "wka": "kbv_code_dosage_form_wka",
            "wkm": "kbv_code_dosage_form_wkm",
            "wue": "kbv_code_dosage_form_wue",
            "xdg": "kbv_code_dosage_form_xdg",
            "xds": "kbv_code_dosage_form_xds",
            "xfe": "kbv_code_dosage_form_xfe",
            "xgm": "kbv_code_dosage_form_xgm",
            "xha": "kbv_code_dosage_form_xha",
            "xhs": "kbv_code_dosage_form_xhs",
            "xnc": "kbv_code_dosage_form_xnc",
            "xpk": "kbv_code_dosage_form_xpk",
            "xtc": "kbv_code_dosage_form_xtc",
            "zam": "kbv_code_dosage_form_zam",
            "zbu": "kbv_code_dosage_form_zbu",
            "zcr": "kbv_code_dosage_form_zcr",
            "zge": "kbv_code_dosage_form_zge",
            "zka": "kbv_code_dosage_form_zka",
            "zpa": "kbv_code_dosage_form_zpa",
        ]
        return mapping[key.lowercased()]
    }
}
