#!/bin/sh

# scripts/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -ev

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  hash brew 2>/dev/null || {
    echo >&2 "The command 'brew' is required but not installed. See https://brew.sh for installation guidelines.";
    exit 1;
  }

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f "Gemfile" ]; then
  hash bundle 2>/dev/null || {
    echo "==> Installing Bundler 2.1.4…"
    gem install bundler -v 2.1.4 --no-document --quiet
  }
  echo "==> Installing gem dependencies…"
  bundle install --system
fi
