#!/bin/sh

# scripts/cibuild: Setup environment for CI and run tests. This is primarily
#                 designed to run on the continuous integration server.

BUILD_TYPE=${1-Release}

set -ev

cd "$(dirname "$0")/.."

echo "CI started at…"
date "+%H:%M:%S"

# Setup project
scripts/setup ${BUILD_TYPE}

# Lint
echo "Linting"
date "+%H:%M:%S"
scripts/lint

# run tests
echo "Running tests…"
date "+%H:%M:%S"
scripts/test

# run cibuild.
echo "Create build"
date "+%H:%M:%S"
scripts/build ${BUILD_TYPE}

echo "Done"
date "+%H:%M:%S"
