#!/bin/sh

# scripts/lint: Run lint for application.

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Running static analysis…"

mint run swiftformat . --config .swiftformat --lint
mint run swiftlint lint --strict --quiet

[[ ! "$(swiftgen config run)" =~ "written" ]] || {
 echo "Linting failed: uncommitted swiftgen changes.\nRun:\tswiftgen\nand commit your changes."
 exit 1
}
