#!/bin/sh
# scripts/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -ev

cd "$(dirname "$0")/.."

scripts/bootstrap

CONFIG=${1-Debug}
bundle exec fastlane setup configuration:${CONFIG}

# These files must exist for sourcery to work 
# (Sourcery tries to read the symbolic link (e.g. Sources/eRpApp/development.env), but it fails because it's a symbolic link to a non-existing file)
touch development.env
touch development.apikeys.env
touch development.static.env
